version: '3.9'
services:

  lb:
    build:
      context: ./load_balancer
      dockerfile: Dockerfile
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./load_balancer:/usr/share/nginx/html
      - ./load_balancer/config/nginx.conf:/etc/nginx.conf
      - ./load_balancer/nginx:/var/www/html
      - ./load_balancer/app:/var/www/log
      - ./load_balancer/nginx/logs:/var/log/nginx
    networks:
      app-network:
        ipv4_address: 192.168.100.20

  oathkeeper:
    build:
      context: ./oathkeeper
      dockerfile: Dockerfile
    tty: true
    ports:
      - '9800:9800'
    volumes:
      - ./oathkeeper:/usr/src/app
    networks:
      app-network:
        ipv4_address: 192.168.100.30

  core_manager:
    # Curation Manager
    build:
      context: ./CoreManager
      dockerfile: Dockerfile
    ports:
      - '5020:5020'
    environment:
      timezone: 'Asia/Tokyo'
    tty: true
    volumes:
      - './coreManager:/app'
    depends_on:
      - core_database
    networks:
      app-network:
        ipv4_address: 192.168.100.15

  curiosity:
    # Explorer by Curiosity
    build:
      context: ./Curiosity
      dockerfile: Dockerfile
    ports:
      - '37936:37936'
    environment:
      timezone: 'Asia/Tokyo'
    tty: true
    volumes:
      - './curiosity:/app'
    depends_on:
      - core_database
    networks:
      app-network:
        ipv4_address: 192.168.100.2

  feed_flare:
    # Feed collector
    build:
      context: ./FeedFlare
      dockerfile: Dockerfile
    ports:
      - '9100:9100'
    environment:
      timezone: 'Asia/Tokyo'
    tty: true
    volumes:
      - './FeedFlare/FeedFlare:/usr/src/app'
    depends_on:
      - core_database
    networks:
      app-network:
        ipv4_address: 192.168.100.3

  info_island:
    # Web Frontend
    build:
      context: ./InfoIsland
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
      - '4173:4173'
    environment:
      timezone: 'Asia/Tokyo'
    tty: true
    volumes:
      - './InfoIsland/InfoIsland:/usr/src/app'
    depends_on:
      - core_database
    networks:
      app-network:
        ipv4_address: 192.168.100.4

  insight_stream:
    # Feed Stream
    build:
      context: ./InsightStream
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    tty: true
    volumes:
      - './InsightStream/InsightStream:/usr/src/app'
    depends_on:
      - core_database
    networks:
      app-network:
        ipv4_address: 192.168.100.5

  slate_flex:
    # Note taking
    build:
      context: ./SlateFlex
      dockerfile: Dockerfile
    ports:
      - '6000:6000'
    tty: true
    volumes:
      - ./slateFlex:/app
    depends_on:
      - core_database
    networks:
      app-network:
        ipv4_address: 192.168.100.6

  feed_spark:
    # Curation Manager
    build:
      context: ./FeedSpark
      dockerfile: Dockerfile
    ports:
      - '5010:5010'
    environment:
      timezone: 'Asia/Tokyo'
    tty: true
    volumes:
      - './FeedSpark:/app'
    depends_on:
      - core_database
    networks:
      app-network:
        ipv4_address: 192.168.100.7
        
  feed_harmony:
    build:
      context: ./FeedHarmony
      dockerfile: Dockerfile
    ports:
      - '5100:5100'
    environment:
      timezone: 'Asia/Tokyo'
    tty: true
    volumes:
      - './FeedHarmony:/app'
    depends_on:
      - core_database
    networks:
      app-network:
        ipv4_address: 192.168.100.8

  core_database:
    # Database
    build:
      context: ./CoreDatabase
      dockerfile: Dockerfile
    container_name: core_database
    ports:
      - '3306:3306'
    tty: true
    volumes:
      - './CoreDatabase/mysql/data:/var/lib/mysql'
      - './CoreDatabase/init:/docker-entrypoint-initdb.d'
    environment:
      timezone: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      app-network:
        ipv4_address: 192.168.100.10

  oath_db:
    # Database
    build:
      context: ./oath_db
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    tty: true
    volumes:
      - './oath_db/init/create_oath_db.sql:/docker-entrypoint-initdb.d/create_oath_db.sql'
      - './oath_db/postgresql/data:/var/lib/postgresql/data'
    environment:
      timezone: 'Asia/Tokyo'
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      app-network:
        ipv4_address: 192.168.100.60

networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
