// Code generated by ent, DO NOT EDIT.

package feedaudittraillog

import (
	"time"
)

const (
	// Label holds the string label denoting the feedaudittraillog type in the database.
	Label = "feed_audit_trail_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAction holds the string denoting the action edge name in mutations.
	EdgeAction = "action"
	// Table holds the table name of the feedaudittraillog in the database.
	Table = "feed_audit_trail_logs"
	// ActionTable is the table that holds the action relation/edge.
	ActionTable = "feed_audit_trail_logs"
	// ActionInverseTable is the table name for the FeedAuditTrailAction entity.
	// It exists in this package in order to avoid circular dependency with the "feedaudittrailaction" package.
	ActionInverseTable = "feed_audit_trail_actions"
	// ActionColumn is the table column denoting the action relation/edge.
	ActionColumn = "action_id"
)

// Columns holds all SQL columns for feedaudittraillog fields.
var Columns = []string{
	FieldID,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "feed_audit_trail_logs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"action_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
