// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FollowList is the predicate function for followlist builders.
type FollowList func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
