// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"insightstream/ent/feedaudittrail"
	"insightstream/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FeedAuditTrailQuery is the builder for querying FeedAuditTrail entities.
type FeedAuditTrailQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	inters     []Interceptor
	predicates []predicate.FeedAuditTrail
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FeedAuditTrailQuery builder.
func (fatq *FeedAuditTrailQuery) Where(ps ...predicate.FeedAuditTrail) *FeedAuditTrailQuery {
	fatq.predicates = append(fatq.predicates, ps...)
	return fatq
}

// Limit the number of records to be returned by this query.
func (fatq *FeedAuditTrailQuery) Limit(limit int) *FeedAuditTrailQuery {
	fatq.limit = &limit
	return fatq
}

// Offset to start from.
func (fatq *FeedAuditTrailQuery) Offset(offset int) *FeedAuditTrailQuery {
	fatq.offset = &offset
	return fatq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fatq *FeedAuditTrailQuery) Unique(unique bool) *FeedAuditTrailQuery {
	fatq.unique = &unique
	return fatq
}

// Order specifies how the records should be ordered.
func (fatq *FeedAuditTrailQuery) Order(o ...OrderFunc) *FeedAuditTrailQuery {
	fatq.order = append(fatq.order, o...)
	return fatq
}

// First returns the first FeedAuditTrail entity from the query.
// Returns a *NotFoundError when no FeedAuditTrail was found.
func (fatq *FeedAuditTrailQuery) First(ctx context.Context) (*FeedAuditTrail, error) {
	nodes, err := fatq.Limit(1).All(newQueryContext(ctx, TypeFeedAuditTrail, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{feedaudittrail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fatq *FeedAuditTrailQuery) FirstX(ctx context.Context) *FeedAuditTrail {
	node, err := fatq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FeedAuditTrail ID from the query.
// Returns a *NotFoundError when no FeedAuditTrail ID was found.
func (fatq *FeedAuditTrailQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fatq.Limit(1).IDs(newQueryContext(ctx, TypeFeedAuditTrail, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{feedaudittrail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fatq *FeedAuditTrailQuery) FirstIDX(ctx context.Context) int {
	id, err := fatq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FeedAuditTrail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FeedAuditTrail entity is found.
// Returns a *NotFoundError when no FeedAuditTrail entities are found.
func (fatq *FeedAuditTrailQuery) Only(ctx context.Context) (*FeedAuditTrail, error) {
	nodes, err := fatq.Limit(2).All(newQueryContext(ctx, TypeFeedAuditTrail, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{feedaudittrail.Label}
	default:
		return nil, &NotSingularError{feedaudittrail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fatq *FeedAuditTrailQuery) OnlyX(ctx context.Context) *FeedAuditTrail {
	node, err := fatq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FeedAuditTrail ID in the query.
// Returns a *NotSingularError when more than one FeedAuditTrail ID is found.
// Returns a *NotFoundError when no entities are found.
func (fatq *FeedAuditTrailQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fatq.Limit(2).IDs(newQueryContext(ctx, TypeFeedAuditTrail, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{feedaudittrail.Label}
	default:
		err = &NotSingularError{feedaudittrail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fatq *FeedAuditTrailQuery) OnlyIDX(ctx context.Context) int {
	id, err := fatq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FeedAuditTrails.
func (fatq *FeedAuditTrailQuery) All(ctx context.Context) ([]*FeedAuditTrail, error) {
	ctx = newQueryContext(ctx, TypeFeedAuditTrail, "All")
	if err := fatq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FeedAuditTrail, *FeedAuditTrailQuery]()
	return withInterceptors[[]*FeedAuditTrail](ctx, fatq, qr, fatq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fatq *FeedAuditTrailQuery) AllX(ctx context.Context) []*FeedAuditTrail {
	nodes, err := fatq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FeedAuditTrail IDs.
func (fatq *FeedAuditTrailQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = newQueryContext(ctx, TypeFeedAuditTrail, "IDs")
	if err := fatq.Select(feedaudittrail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fatq *FeedAuditTrailQuery) IDsX(ctx context.Context) []int {
	ids, err := fatq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fatq *FeedAuditTrailQuery) Count(ctx context.Context) (int, error) {
	ctx = newQueryContext(ctx, TypeFeedAuditTrail, "Count")
	if err := fatq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fatq, querierCount[*FeedAuditTrailQuery](), fatq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fatq *FeedAuditTrailQuery) CountX(ctx context.Context) int {
	count, err := fatq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fatq *FeedAuditTrailQuery) Exist(ctx context.Context) (bool, error) {
	ctx = newQueryContext(ctx, TypeFeedAuditTrail, "Exist")
	switch _, err := fatq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fatq *FeedAuditTrailQuery) ExistX(ctx context.Context) bool {
	exist, err := fatq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FeedAuditTrailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fatq *FeedAuditTrailQuery) Clone() *FeedAuditTrailQuery {
	if fatq == nil {
		return nil
	}
	return &FeedAuditTrailQuery{
		config:     fatq.config,
		limit:      fatq.limit,
		offset:     fatq.offset,
		order:      append([]OrderFunc{}, fatq.order...),
		inters:     append([]Interceptor{}, fatq.inters...),
		predicates: append([]predicate.FeedAuditTrail{}, fatq.predicates...),
		// clone intermediate query.
		sql:    fatq.sql.Clone(),
		path:   fatq.path,
		unique: fatq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UpdatedAt time.Time `json:"updated_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FeedAuditTrail.Query().
//		GroupBy(feedaudittrail.FieldUpdatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fatq *FeedAuditTrailQuery) GroupBy(field string, fields ...string) *FeedAuditTrailGroupBy {
	fatq.fields = append([]string{field}, fields...)
	grbuild := &FeedAuditTrailGroupBy{build: fatq}
	grbuild.flds = &fatq.fields
	grbuild.label = feedaudittrail.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UpdatedAt time.Time `json:"updated_at,omitempty"`
//	}
//
//	client.FeedAuditTrail.Query().
//		Select(feedaudittrail.FieldUpdatedAt).
//		Scan(ctx, &v)
func (fatq *FeedAuditTrailQuery) Select(fields ...string) *FeedAuditTrailSelect {
	fatq.fields = append(fatq.fields, fields...)
	sbuild := &FeedAuditTrailSelect{FeedAuditTrailQuery: fatq}
	sbuild.label = feedaudittrail.Label
	sbuild.flds, sbuild.scan = &fatq.fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FeedAuditTrailSelect configured with the given aggregations.
func (fatq *FeedAuditTrailQuery) Aggregate(fns ...AggregateFunc) *FeedAuditTrailSelect {
	return fatq.Select().Aggregate(fns...)
}

func (fatq *FeedAuditTrailQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fatq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fatq); err != nil {
				return err
			}
		}
	}
	for _, f := range fatq.fields {
		if !feedaudittrail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fatq.path != nil {
		prev, err := fatq.path(ctx)
		if err != nil {
			return err
		}
		fatq.sql = prev
	}
	return nil
}

func (fatq *FeedAuditTrailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FeedAuditTrail, error) {
	var (
		nodes = []*FeedAuditTrail{}
		_spec = fatq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FeedAuditTrail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FeedAuditTrail{config: fatq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fatq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (fatq *FeedAuditTrailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fatq.querySpec()
	_spec.Node.Columns = fatq.fields
	if len(fatq.fields) > 0 {
		_spec.Unique = fatq.unique != nil && *fatq.unique
	}
	return sqlgraph.CountNodes(ctx, fatq.driver, _spec)
}

func (fatq *FeedAuditTrailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   feedaudittrail.Table,
			Columns: feedaudittrail.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: feedaudittrail.FieldID,
			},
		},
		From:   fatq.sql,
		Unique: true,
	}
	if unique := fatq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := fatq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, feedaudittrail.FieldID)
		for i := range fields {
			if fields[i] != feedaudittrail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fatq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fatq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fatq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fatq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fatq *FeedAuditTrailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fatq.driver.Dialect())
	t1 := builder.Table(feedaudittrail.Table)
	columns := fatq.fields
	if len(columns) == 0 {
		columns = feedaudittrail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fatq.sql != nil {
		selector = fatq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fatq.unique != nil && *fatq.unique {
		selector.Distinct()
	}
	for _, p := range fatq.predicates {
		p(selector)
	}
	for _, p := range fatq.order {
		p(selector)
	}
	if offset := fatq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fatq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FeedAuditTrailGroupBy is the group-by builder for FeedAuditTrail entities.
type FeedAuditTrailGroupBy struct {
	selector
	build *FeedAuditTrailQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fatgb *FeedAuditTrailGroupBy) Aggregate(fns ...AggregateFunc) *FeedAuditTrailGroupBy {
	fatgb.fns = append(fatgb.fns, fns...)
	return fatgb
}

// Scan applies the selector query and scans the result into the given value.
func (fatgb *FeedAuditTrailGroupBy) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeFeedAuditTrail, "GroupBy")
	if err := fatgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FeedAuditTrailQuery, *FeedAuditTrailGroupBy](ctx, fatgb.build, fatgb, fatgb.build.inters, v)
}

func (fatgb *FeedAuditTrailGroupBy) sqlScan(ctx context.Context, root *FeedAuditTrailQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fatgb.fns))
	for _, fn := range fatgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fatgb.flds)+len(fatgb.fns))
		for _, f := range *fatgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fatgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fatgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FeedAuditTrailSelect is the builder for selecting fields of FeedAuditTrail entities.
type FeedAuditTrailSelect struct {
	*FeedAuditTrailQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fats *FeedAuditTrailSelect) Aggregate(fns ...AggregateFunc) *FeedAuditTrailSelect {
	fats.fns = append(fats.fns, fns...)
	return fats
}

// Scan applies the selector query and scans the result into the given value.
func (fats *FeedAuditTrailSelect) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeFeedAuditTrail, "Select")
	if err := fats.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FeedAuditTrailQuery, *FeedAuditTrailSelect](ctx, fats.FeedAuditTrailQuery, fats, fats.inters, v)
}

func (fats *FeedAuditTrailSelect) sqlScan(ctx context.Context, root *FeedAuditTrailQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fats.fns))
	for _, fn := range fats.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fats.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fats.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
