// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"insightstream/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	entfeeds "insightstream/ent/feeds"
)

// FeedsQuery is the builder for querying Feeds entities.
type FeedsQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	inters     []Interceptor
	predicates []predicate.Feeds
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FeedsQuery builder.
func (fq *FeedsQuery) Where(ps ...predicate.Feeds) *FeedsQuery {
	fq.predicates = append(fq.predicates, ps...)
	return fq
}

// Limit the number of records to be returned by this query.
func (fq *FeedsQuery) Limit(limit int) *FeedsQuery {
	fq.limit = &limit
	return fq
}

// Offset to start from.
func (fq *FeedsQuery) Offset(offset int) *FeedsQuery {
	fq.offset = &offset
	return fq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fq *FeedsQuery) Unique(unique bool) *FeedsQuery {
	fq.unique = &unique
	return fq
}

// Order specifies how the records should be ordered.
func (fq *FeedsQuery) Order(o ...OrderFunc) *FeedsQuery {
	fq.order = append(fq.order, o...)
	return fq
}

// First returns the first Feeds entity from the query.
// Returns a *NotFoundError when no Feeds was found.
func (fq *FeedsQuery) First(ctx context.Context) (*Feeds, error) {
	nodes, err := fq.Limit(1).All(newQueryContext(ctx, TypeFeeds, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entfeeds.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fq *FeedsQuery) FirstX(ctx context.Context) *Feeds {
	node, err := fq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Feeds ID from the query.
// Returns a *NotFoundError when no Feeds ID was found.
func (fq *FeedsQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = fq.Limit(1).IDs(newQueryContext(ctx, TypeFeeds, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entfeeds.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fq *FeedsQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := fq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Feeds entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Feeds entity is found.
// Returns a *NotFoundError when no Feeds entities are found.
func (fq *FeedsQuery) Only(ctx context.Context) (*Feeds, error) {
	nodes, err := fq.Limit(2).All(newQueryContext(ctx, TypeFeeds, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entfeeds.Label}
	default:
		return nil, &NotSingularError{entfeeds.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fq *FeedsQuery) OnlyX(ctx context.Context) *Feeds {
	node, err := fq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Feeds ID in the query.
// Returns a *NotSingularError when more than one Feeds ID is found.
// Returns a *NotFoundError when no entities are found.
func (fq *FeedsQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = fq.Limit(2).IDs(newQueryContext(ctx, TypeFeeds, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entfeeds.Label}
	default:
		err = &NotSingularError{entfeeds.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fq *FeedsQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := fq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FeedsSlice.
func (fq *FeedsQuery) All(ctx context.Context) ([]*Feeds, error) {
	ctx = newQueryContext(ctx, TypeFeeds, "All")
	if err := fq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Feeds, *FeedsQuery]()
	return withInterceptors[[]*Feeds](ctx, fq, qr, fq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fq *FeedsQuery) AllX(ctx context.Context) []*Feeds {
	nodes, err := fq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Feeds IDs.
func (fq *FeedsQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	ctx = newQueryContext(ctx, TypeFeeds, "IDs")
	if err := fq.Select(entfeeds.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fq *FeedsQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := fq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fq *FeedsQuery) Count(ctx context.Context) (int, error) {
	ctx = newQueryContext(ctx, TypeFeeds, "Count")
	if err := fq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fq, querierCount[*FeedsQuery](), fq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fq *FeedsQuery) CountX(ctx context.Context) int {
	count, err := fq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fq *FeedsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = newQueryContext(ctx, TypeFeeds, "Exist")
	switch _, err := fq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fq *FeedsQuery) ExistX(ctx context.Context) bool {
	exist, err := fq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FeedsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fq *FeedsQuery) Clone() *FeedsQuery {
	if fq == nil {
		return nil
	}
	return &FeedsQuery{
		config:     fq.config,
		limit:      fq.limit,
		offset:     fq.offset,
		order:      append([]OrderFunc{}, fq.order...),
		inters:     append([]Interceptor{}, fq.inters...),
		predicates: append([]predicate.Feeds{}, fq.predicates...),
		// clone intermediate query.
		sql:    fq.sql.Clone(),
		path:   fq.path,
		unique: fq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SiteURL string `json:"site_url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Feeds.Query().
//		GroupBy(entfeeds.FieldSiteURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fq *FeedsQuery) GroupBy(field string, fields ...string) *FeedsGroupBy {
	fq.fields = append([]string{field}, fields...)
	grbuild := &FeedsGroupBy{build: fq}
	grbuild.flds = &fq.fields
	grbuild.label = entfeeds.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SiteURL string `json:"site_url,omitempty"`
//	}
//
//	client.Feeds.Query().
//		Select(entfeeds.FieldSiteURL).
//		Scan(ctx, &v)
func (fq *FeedsQuery) Select(fields ...string) *FeedsSelect {
	fq.fields = append(fq.fields, fields...)
	sbuild := &FeedsSelect{FeedsQuery: fq}
	sbuild.label = entfeeds.Label
	sbuild.flds, sbuild.scan = &fq.fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FeedsSelect configured with the given aggregations.
func (fq *FeedsQuery) Aggregate(fns ...AggregateFunc) *FeedsSelect {
	return fq.Select().Aggregate(fns...)
}

func (fq *FeedsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fq); err != nil {
				return err
			}
		}
	}
	for _, f := range fq.fields {
		if !entfeeds.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fq.path != nil {
		prev, err := fq.path(ctx)
		if err != nil {
			return err
		}
		fq.sql = prev
	}
	return nil
}

func (fq *FeedsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Feeds, error) {
	var (
		nodes = []*Feeds{}
		_spec = fq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Feeds).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Feeds{config: fq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (fq *FeedsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fq.querySpec()
	_spec.Node.Columns = fq.fields
	if len(fq.fields) > 0 {
		_spec.Unique = fq.unique != nil && *fq.unique
	}
	return sqlgraph.CountNodes(ctx, fq.driver, _spec)
}

func (fq *FeedsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   entfeeds.Table,
			Columns: entfeeds.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: entfeeds.FieldID,
			},
		},
		From:   fq.sql,
		Unique: true,
	}
	if unique := fq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := fq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entfeeds.FieldID)
		for i := range fields {
			if fields[i] != entfeeds.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fq *FeedsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fq.driver.Dialect())
	t1 := builder.Table(entfeeds.Table)
	columns := fq.fields
	if len(columns) == 0 {
		columns = entfeeds.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fq.sql != nil {
		selector = fq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fq.unique != nil && *fq.unique {
		selector.Distinct()
	}
	for _, p := range fq.predicates {
		p(selector)
	}
	for _, p := range fq.order {
		p(selector)
	}
	if offset := fq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FeedsGroupBy is the group-by builder for Feeds entities.
type FeedsGroupBy struct {
	selector
	build *FeedsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fgb *FeedsGroupBy) Aggregate(fns ...AggregateFunc) *FeedsGroupBy {
	fgb.fns = append(fgb.fns, fns...)
	return fgb
}

// Scan applies the selector query and scans the result into the given value.
func (fgb *FeedsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeFeeds, "GroupBy")
	if err := fgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FeedsQuery, *FeedsGroupBy](ctx, fgb.build, fgb, fgb.build.inters, v)
}

func (fgb *FeedsGroupBy) sqlScan(ctx context.Context, root *FeedsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fgb.fns))
	for _, fn := range fgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fgb.flds)+len(fgb.fns))
		for _, f := range *fgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FeedsSelect is the builder for selecting fields of Feeds entities.
type FeedsSelect struct {
	*FeedsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fs *FeedsSelect) Aggregate(fns ...AggregateFunc) *FeedsSelect {
	fs.fns = append(fs.fns, fns...)
	return fs
}

// Scan applies the selector query and scans the result into the given value.
func (fs *FeedsSelect) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeFeeds, "Select")
	if err := fs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FeedsQuery, *FeedsSelect](ctx, fs.FeedsQuery, fs, fs.inters, v)
}

func (fs *FeedsSelect) sqlScan(ctx context.Context, root *FeedsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fs.fns))
	for _, fn := range fs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
