// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"insightstream/domain/baseFeeds"
	"insightstream/ent/followlists"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FollowListsCreate is the builder for creating a FollowLists entity.
type FollowListsCreate struct {
	config
	mutation *FollowListsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUUID sets the "uuid" field.
func (flc *FollowListsCreate) SetUUID(u uuid.UUID) *FollowListsCreate {
	flc.mutation.SetUUID(u)
	return flc
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableUUID(u *uuid.UUID) *FollowListsCreate {
	if u != nil {
		flc.SetUUID(*u)
	}
	return flc
}

// SetXMLVersion sets the "xml_version" field.
func (flc *FollowListsCreate) SetXMLVersion(i int8) *FollowListsCreate {
	flc.mutation.SetXMLVersion(i)
	return flc
}

// SetNillableXMLVersion sets the "xml_version" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableXMLVersion(i *int8) *FollowListsCreate {
	if i != nil {
		flc.SetXMLVersion(*i)
	}
	return flc
}

// SetRssVersion sets the "rss_version" field.
func (flc *FollowListsCreate) SetRssVersion(i int8) *FollowListsCreate {
	flc.mutation.SetRssVersion(i)
	return flc
}

// SetNillableRssVersion sets the "rss_version" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableRssVersion(i *int8) *FollowListsCreate {
	if i != nil {
		flc.SetRssVersion(*i)
	}
	return flc
}

// SetURL sets the "url" field.
func (flc *FollowListsCreate) SetURL(s string) *FollowListsCreate {
	flc.mutation.SetURL(s)
	return flc
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableURL(s *string) *FollowListsCreate {
	if s != nil {
		flc.SetURL(*s)
	}
	return flc
}

// SetTitle sets the "title" field.
func (flc *FollowListsCreate) SetTitle(s string) *FollowListsCreate {
	flc.mutation.SetTitle(s)
	return flc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableTitle(s *string) *FollowListsCreate {
	if s != nil {
		flc.SetTitle(*s)
	}
	return flc
}

// SetDescription sets the "description" field.
func (flc *FollowListsCreate) SetDescription(s string) *FollowListsCreate {
	flc.mutation.SetDescription(s)
	return flc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableDescription(s *string) *FollowListsCreate {
	if s != nil {
		flc.SetDescription(*s)
	}
	return flc
}

// SetLink sets the "link" field.
func (flc *FollowListsCreate) SetLink(s string) *FollowListsCreate {
	flc.mutation.SetLink(s)
	return flc
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableLink(s *string) *FollowListsCreate {
	if s != nil {
		flc.SetLink(*s)
	}
	return flc
}

// SetLinks sets the "links" field.
func (flc *FollowListsCreate) SetLinks(bfl baseFeeds.FeedLink) *FollowListsCreate {
	flc.mutation.SetLinks(bfl)
	return flc
}

// SetNillableLinks sets the "links" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableLinks(bfl *baseFeeds.FeedLink) *FollowListsCreate {
	if bfl != nil {
		flc.SetLinks(*bfl)
	}
	return flc
}

// SetItemDescription sets the "item_description" field.
func (flc *FollowListsCreate) SetItemDescription(bfi []baseFeeds.FeedItem) *FollowListsCreate {
	flc.mutation.SetItemDescription(bfi)
	return flc
}

// SetLanguage sets the "language" field.
func (flc *FollowListsCreate) SetLanguage(s string) *FollowListsCreate {
	flc.mutation.SetLanguage(s)
	return flc
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableLanguage(s *string) *FollowListsCreate {
	if s != nil {
		flc.SetLanguage(*s)
	}
	return flc
}

// SetDtCreated sets the "dt_created" field.
func (flc *FollowListsCreate) SetDtCreated(t time.Time) *FollowListsCreate {
	flc.mutation.SetDtCreated(t)
	return flc
}

// SetNillableDtCreated sets the "dt_created" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableDtCreated(t *time.Time) *FollowListsCreate {
	if t != nil {
		flc.SetDtCreated(*t)
	}
	return flc
}

// SetDtUpdated sets the "dt_updated" field.
func (flc *FollowListsCreate) SetDtUpdated(t time.Time) *FollowListsCreate {
	flc.mutation.SetDtUpdated(t)
	return flc
}

// SetNillableDtUpdated sets the "dt_updated" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableDtUpdated(t *time.Time) *FollowListsCreate {
	if t != nil {
		flc.SetDtUpdated(*t)
	}
	return flc
}

// SetDtLastInserted sets the "dt_last_inserted" field.
func (flc *FollowListsCreate) SetDtLastInserted(t time.Time) *FollowListsCreate {
	flc.mutation.SetDtLastInserted(t)
	return flc
}

// SetNillableDtLastInserted sets the "dt_last_inserted" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableDtLastInserted(t *time.Time) *FollowListsCreate {
	if t != nil {
		flc.SetDtLastInserted(*t)
	}
	return flc
}

// SetFeedCategory sets the "feed_category" field.
func (flc *FollowListsCreate) SetFeedCategory(i int) *FollowListsCreate {
	flc.mutation.SetFeedCategory(i)
	return flc
}

// SetNillableFeedCategory sets the "feed_category" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableFeedCategory(i *int) *FollowListsCreate {
	if i != nil {
		flc.SetFeedCategory(*i)
	}
	return flc
}

// SetIsActive sets the "is_active" field.
func (flc *FollowListsCreate) SetIsActive(b bool) *FollowListsCreate {
	flc.mutation.SetIsActive(b)
	return flc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableIsActive(b *bool) *FollowListsCreate {
	if b != nil {
		flc.SetIsActive(*b)
	}
	return flc
}

// SetIsFavorite sets the "is_favorite" field.
func (flc *FollowListsCreate) SetIsFavorite(b bool) *FollowListsCreate {
	flc.mutation.SetIsFavorite(b)
	return flc
}

// SetNillableIsFavorite sets the "is_favorite" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableIsFavorite(b *bool) *FollowListsCreate {
	if b != nil {
		flc.SetIsFavorite(*b)
	}
	return flc
}

// SetIsRead sets the "is_read" field.
func (flc *FollowListsCreate) SetIsRead(b bool) *FollowListsCreate {
	flc.mutation.SetIsRead(b)
	return flc
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableIsRead(b *bool) *FollowListsCreate {
	if b != nil {
		flc.SetIsRead(*b)
	}
	return flc
}

// SetIsUpdated sets the "is_updated" field.
func (flc *FollowListsCreate) SetIsUpdated(b bool) *FollowListsCreate {
	flc.mutation.SetIsUpdated(b)
	return flc
}

// SetNillableIsUpdated sets the "is_updated" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableIsUpdated(b *bool) *FollowListsCreate {
	if b != nil {
		flc.SetIsUpdated(*b)
	}
	return flc
}

// Mutation returns the FollowListsMutation object of the builder.
func (flc *FollowListsCreate) Mutation() *FollowListsMutation {
	return flc.mutation
}

// Save creates the FollowLists in the database.
func (flc *FollowListsCreate) Save(ctx context.Context) (*FollowLists, error) {
	flc.defaults()
	return withHooks[*FollowLists, FollowListsMutation](ctx, flc.sqlSave, flc.mutation, flc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (flc *FollowListsCreate) SaveX(ctx context.Context) *FollowLists {
	v, err := flc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (flc *FollowListsCreate) Exec(ctx context.Context) error {
	_, err := flc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (flc *FollowListsCreate) ExecX(ctx context.Context) {
	if err := flc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (flc *FollowListsCreate) defaults() {
	if _, ok := flc.mutation.UUID(); !ok {
		v := followlists.DefaultUUID()
		flc.mutation.SetUUID(v)
	}
	if _, ok := flc.mutation.XMLVersion(); !ok {
		v := followlists.DefaultXMLVersion
		flc.mutation.SetXMLVersion(v)
	}
	if _, ok := flc.mutation.RssVersion(); !ok {
		v := followlists.DefaultRssVersion
		flc.mutation.SetRssVersion(v)
	}
	if _, ok := flc.mutation.URL(); !ok {
		v := followlists.DefaultURL
		flc.mutation.SetURL(v)
	}
	if _, ok := flc.mutation.Title(); !ok {
		v := followlists.DefaultTitle
		flc.mutation.SetTitle(v)
	}
	if _, ok := flc.mutation.Description(); !ok {
		v := followlists.DefaultDescription
		flc.mutation.SetDescription(v)
	}
	if _, ok := flc.mutation.Link(); !ok {
		v := followlists.DefaultLink
		flc.mutation.SetLink(v)
	}
	if _, ok := flc.mutation.Links(); !ok {
		v := followlists.DefaultLinks
		flc.mutation.SetLinks(v)
	}
	if _, ok := flc.mutation.Language(); !ok {
		v := followlists.DefaultLanguage
		flc.mutation.SetLanguage(v)
	}
	if _, ok := flc.mutation.DtCreated(); !ok {
		v := followlists.DefaultDtCreated
		flc.mutation.SetDtCreated(v)
	}
	if _, ok := flc.mutation.DtUpdated(); !ok {
		v := followlists.DefaultDtUpdated
		flc.mutation.SetDtUpdated(v)
	}
	if _, ok := flc.mutation.DtLastInserted(); !ok {
		v := followlists.DefaultDtLastInserted
		flc.mutation.SetDtLastInserted(v)
	}
	if _, ok := flc.mutation.FeedCategory(); !ok {
		v := followlists.DefaultFeedCategory
		flc.mutation.SetFeedCategory(v)
	}
	if _, ok := flc.mutation.IsActive(); !ok {
		v := followlists.DefaultIsActive
		flc.mutation.SetIsActive(v)
	}
	if _, ok := flc.mutation.IsFavorite(); !ok {
		v := followlists.DefaultIsFavorite
		flc.mutation.SetIsFavorite(v)
	}
	if _, ok := flc.mutation.IsRead(); !ok {
		v := followlists.DefaultIsRead
		flc.mutation.SetIsRead(v)
	}
	if _, ok := flc.mutation.IsUpdated(); !ok {
		v := followlists.DefaultIsUpdated
		flc.mutation.SetIsUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (flc *FollowListsCreate) check() error {
	if _, ok := flc.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "FollowLists.uuid"`)}
	}
	if _, ok := flc.mutation.XMLVersion(); !ok {
		return &ValidationError{Name: "xml_version", err: errors.New(`ent: missing required field "FollowLists.xml_version"`)}
	}
	if _, ok := flc.mutation.RssVersion(); !ok {
		return &ValidationError{Name: "rss_version", err: errors.New(`ent: missing required field "FollowLists.rss_version"`)}
	}
	if _, ok := flc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "FollowLists.url"`)}
	}
	if v, ok := flc.mutation.URL(); ok {
		if err := followlists.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "FollowLists.url": %w`, err)}
		}
	}
	if _, ok := flc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "FollowLists.title"`)}
	}
	if _, ok := flc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "FollowLists.description"`)}
	}
	if _, ok := flc.mutation.Link(); !ok {
		return &ValidationError{Name: "link", err: errors.New(`ent: missing required field "FollowLists.link"`)}
	}
	if _, ok := flc.mutation.Links(); !ok {
		return &ValidationError{Name: "links", err: errors.New(`ent: missing required field "FollowLists.links"`)}
	}
	if _, ok := flc.mutation.ItemDescription(); !ok {
		return &ValidationError{Name: "item_description", err: errors.New(`ent: missing required field "FollowLists.item_description"`)}
	}
	if _, ok := flc.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "FollowLists.language"`)}
	}
	if v, ok := flc.mutation.Language(); ok {
		if err := followlists.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "FollowLists.language": %w`, err)}
		}
	}
	if _, ok := flc.mutation.FeedCategory(); !ok {
		return &ValidationError{Name: "feed_category", err: errors.New(`ent: missing required field "FollowLists.feed_category"`)}
	}
	if _, ok := flc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "FollowLists.is_active"`)}
	}
	if _, ok := flc.mutation.IsFavorite(); !ok {
		return &ValidationError{Name: "is_favorite", err: errors.New(`ent: missing required field "FollowLists.is_favorite"`)}
	}
	if _, ok := flc.mutation.IsRead(); !ok {
		return &ValidationError{Name: "is_read", err: errors.New(`ent: missing required field "FollowLists.is_read"`)}
	}
	if _, ok := flc.mutation.IsUpdated(); !ok {
		return &ValidationError{Name: "is_updated", err: errors.New(`ent: missing required field "FollowLists.is_updated"`)}
	}
	return nil
}

func (flc *FollowListsCreate) sqlSave(ctx context.Context) (*FollowLists, error) {
	if err := flc.check(); err != nil {
		return nil, err
	}
	_node, _spec := flc.createSpec()
	if err := sqlgraph.CreateNode(ctx, flc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	flc.mutation.id = &_node.ID
	flc.mutation.done = true
	return _node, nil
}

func (flc *FollowListsCreate) createSpec() (*FollowLists, *sqlgraph.CreateSpec) {
	var (
		_node = &FollowLists{config: flc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: followlists.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: followlists.FieldID,
			},
		}
	)
	_spec.OnConflict = flc.conflict
	if value, ok := flc.mutation.UUID(); ok {
		_spec.SetField(followlists.FieldUUID, field.TypeUUID, value)
		_node.UUID = value
	}
	if value, ok := flc.mutation.XMLVersion(); ok {
		_spec.SetField(followlists.FieldXMLVersion, field.TypeInt8, value)
		_node.XMLVersion = value
	}
	if value, ok := flc.mutation.RssVersion(); ok {
		_spec.SetField(followlists.FieldRssVersion, field.TypeInt8, value)
		_node.RssVersion = value
	}
	if value, ok := flc.mutation.URL(); ok {
		_spec.SetField(followlists.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := flc.mutation.Title(); ok {
		_spec.SetField(followlists.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := flc.mutation.Description(); ok {
		_spec.SetField(followlists.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := flc.mutation.Link(); ok {
		_spec.SetField(followlists.FieldLink, field.TypeString, value)
		_node.Link = value
	}
	if value, ok := flc.mutation.Links(); ok {
		_spec.SetField(followlists.FieldLinks, field.TypeJSON, value)
		_node.Links = value
	}
	if value, ok := flc.mutation.ItemDescription(); ok {
		_spec.SetField(followlists.FieldItemDescription, field.TypeJSON, value)
		_node.ItemDescription = value
	}
	if value, ok := flc.mutation.Language(); ok {
		_spec.SetField(followlists.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := flc.mutation.DtCreated(); ok {
		_spec.SetField(followlists.FieldDtCreated, field.TypeTime, value)
		_node.DtCreated = value
	}
	if value, ok := flc.mutation.DtUpdated(); ok {
		_spec.SetField(followlists.FieldDtUpdated, field.TypeTime, value)
		_node.DtUpdated = value
	}
	if value, ok := flc.mutation.DtLastInserted(); ok {
		_spec.SetField(followlists.FieldDtLastInserted, field.TypeTime, value)
		_node.DtLastInserted = value
	}
	if value, ok := flc.mutation.FeedCategory(); ok {
		_spec.SetField(followlists.FieldFeedCategory, field.TypeInt, value)
		_node.FeedCategory = value
	}
	if value, ok := flc.mutation.IsActive(); ok {
		_spec.SetField(followlists.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := flc.mutation.IsFavorite(); ok {
		_spec.SetField(followlists.FieldIsFavorite, field.TypeBool, value)
		_node.IsFavorite = value
	}
	if value, ok := flc.mutation.IsRead(); ok {
		_spec.SetField(followlists.FieldIsRead, field.TypeBool, value)
		_node.IsRead = value
	}
	if value, ok := flc.mutation.IsUpdated(); ok {
		_spec.SetField(followlists.FieldIsUpdated, field.TypeBool, value)
		_node.IsUpdated = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FollowLists.Create().
//		SetUUID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FollowListsUpsert) {
//			SetUUID(v+v).
//		}).
//		Exec(ctx)
func (flc *FollowListsCreate) OnConflict(opts ...sql.ConflictOption) *FollowListsUpsertOne {
	flc.conflict = opts
	return &FollowListsUpsertOne{
		create: flc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FollowLists.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (flc *FollowListsCreate) OnConflictColumns(columns ...string) *FollowListsUpsertOne {
	flc.conflict = append(flc.conflict, sql.ConflictColumns(columns...))
	return &FollowListsUpsertOne{
		create: flc,
	}
}

type (
	// FollowListsUpsertOne is the builder for "upsert"-ing
	//  one FollowLists node.
	FollowListsUpsertOne struct {
		create *FollowListsCreate
	}

	// FollowListsUpsert is the "OnConflict" setter.
	FollowListsUpsert struct {
		*sql.UpdateSet
	}
)

// SetUUID sets the "uuid" field.
func (u *FollowListsUpsert) SetUUID(v uuid.UUID) *FollowListsUpsert {
	u.Set(followlists.FieldUUID, v)
	return u
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateUUID() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldUUID)
	return u
}

// SetXMLVersion sets the "xml_version" field.
func (u *FollowListsUpsert) SetXMLVersion(v int8) *FollowListsUpsert {
	u.Set(followlists.FieldXMLVersion, v)
	return u
}

// UpdateXMLVersion sets the "xml_version" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateXMLVersion() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldXMLVersion)
	return u
}

// AddXMLVersion adds v to the "xml_version" field.
func (u *FollowListsUpsert) AddXMLVersion(v int8) *FollowListsUpsert {
	u.Add(followlists.FieldXMLVersion, v)
	return u
}

// SetRssVersion sets the "rss_version" field.
func (u *FollowListsUpsert) SetRssVersion(v int8) *FollowListsUpsert {
	u.Set(followlists.FieldRssVersion, v)
	return u
}

// UpdateRssVersion sets the "rss_version" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateRssVersion() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldRssVersion)
	return u
}

// AddRssVersion adds v to the "rss_version" field.
func (u *FollowListsUpsert) AddRssVersion(v int8) *FollowListsUpsert {
	u.Add(followlists.FieldRssVersion, v)
	return u
}

// SetURL sets the "url" field.
func (u *FollowListsUpsert) SetURL(v string) *FollowListsUpsert {
	u.Set(followlists.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateURL() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldURL)
	return u
}

// SetTitle sets the "title" field.
func (u *FollowListsUpsert) SetTitle(v string) *FollowListsUpsert {
	u.Set(followlists.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateTitle() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *FollowListsUpsert) SetDescription(v string) *FollowListsUpsert {
	u.Set(followlists.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateDescription() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldDescription)
	return u
}

// SetLink sets the "link" field.
func (u *FollowListsUpsert) SetLink(v string) *FollowListsUpsert {
	u.Set(followlists.FieldLink, v)
	return u
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateLink() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldLink)
	return u
}

// SetLinks sets the "links" field.
func (u *FollowListsUpsert) SetLinks(v baseFeeds.FeedLink) *FollowListsUpsert {
	u.Set(followlists.FieldLinks, v)
	return u
}

// UpdateLinks sets the "links" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateLinks() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldLinks)
	return u
}

// SetItemDescription sets the "item_description" field.
func (u *FollowListsUpsert) SetItemDescription(v []baseFeeds.FeedItem) *FollowListsUpsert {
	u.Set(followlists.FieldItemDescription, v)
	return u
}

// UpdateItemDescription sets the "item_description" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateItemDescription() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldItemDescription)
	return u
}

// SetLanguage sets the "language" field.
func (u *FollowListsUpsert) SetLanguage(v string) *FollowListsUpsert {
	u.Set(followlists.FieldLanguage, v)
	return u
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateLanguage() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldLanguage)
	return u
}

// SetDtCreated sets the "dt_created" field.
func (u *FollowListsUpsert) SetDtCreated(v time.Time) *FollowListsUpsert {
	u.Set(followlists.FieldDtCreated, v)
	return u
}

// UpdateDtCreated sets the "dt_created" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateDtCreated() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldDtCreated)
	return u
}

// ClearDtCreated clears the value of the "dt_created" field.
func (u *FollowListsUpsert) ClearDtCreated() *FollowListsUpsert {
	u.SetNull(followlists.FieldDtCreated)
	return u
}

// SetDtUpdated sets the "dt_updated" field.
func (u *FollowListsUpsert) SetDtUpdated(v time.Time) *FollowListsUpsert {
	u.Set(followlists.FieldDtUpdated, v)
	return u
}

// UpdateDtUpdated sets the "dt_updated" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateDtUpdated() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldDtUpdated)
	return u
}

// ClearDtUpdated clears the value of the "dt_updated" field.
func (u *FollowListsUpsert) ClearDtUpdated() *FollowListsUpsert {
	u.SetNull(followlists.FieldDtUpdated)
	return u
}

// SetDtLastInserted sets the "dt_last_inserted" field.
func (u *FollowListsUpsert) SetDtLastInserted(v time.Time) *FollowListsUpsert {
	u.Set(followlists.FieldDtLastInserted, v)
	return u
}

// UpdateDtLastInserted sets the "dt_last_inserted" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateDtLastInserted() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldDtLastInserted)
	return u
}

// ClearDtLastInserted clears the value of the "dt_last_inserted" field.
func (u *FollowListsUpsert) ClearDtLastInserted() *FollowListsUpsert {
	u.SetNull(followlists.FieldDtLastInserted)
	return u
}

// SetFeedCategory sets the "feed_category" field.
func (u *FollowListsUpsert) SetFeedCategory(v int) *FollowListsUpsert {
	u.Set(followlists.FieldFeedCategory, v)
	return u
}

// UpdateFeedCategory sets the "feed_category" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateFeedCategory() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldFeedCategory)
	return u
}

// AddFeedCategory adds v to the "feed_category" field.
func (u *FollowListsUpsert) AddFeedCategory(v int) *FollowListsUpsert {
	u.Add(followlists.FieldFeedCategory, v)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *FollowListsUpsert) SetIsActive(v bool) *FollowListsUpsert {
	u.Set(followlists.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateIsActive() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldIsActive)
	return u
}

// SetIsFavorite sets the "is_favorite" field.
func (u *FollowListsUpsert) SetIsFavorite(v bool) *FollowListsUpsert {
	u.Set(followlists.FieldIsFavorite, v)
	return u
}

// UpdateIsFavorite sets the "is_favorite" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateIsFavorite() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldIsFavorite)
	return u
}

// SetIsRead sets the "is_read" field.
func (u *FollowListsUpsert) SetIsRead(v bool) *FollowListsUpsert {
	u.Set(followlists.FieldIsRead, v)
	return u
}

// UpdateIsRead sets the "is_read" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateIsRead() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldIsRead)
	return u
}

// SetIsUpdated sets the "is_updated" field.
func (u *FollowListsUpsert) SetIsUpdated(v bool) *FollowListsUpsert {
	u.Set(followlists.FieldIsUpdated, v)
	return u
}

// UpdateIsUpdated sets the "is_updated" field to the value that was provided on create.
func (u *FollowListsUpsert) UpdateIsUpdated() *FollowListsUpsert {
	u.SetExcluded(followlists.FieldIsUpdated)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FollowLists.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FollowListsUpsertOne) UpdateNewValues() *FollowListsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FollowLists.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FollowListsUpsertOne) Ignore() *FollowListsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FollowListsUpsertOne) DoNothing() *FollowListsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FollowListsCreate.OnConflict
// documentation for more info.
func (u *FollowListsUpsertOne) Update(set func(*FollowListsUpsert)) *FollowListsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FollowListsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUUID sets the "uuid" field.
func (u *FollowListsUpsertOne) SetUUID(v uuid.UUID) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetUUID(v)
	})
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateUUID() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateUUID()
	})
}

// SetXMLVersion sets the "xml_version" field.
func (u *FollowListsUpsertOne) SetXMLVersion(v int8) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetXMLVersion(v)
	})
}

// AddXMLVersion adds v to the "xml_version" field.
func (u *FollowListsUpsertOne) AddXMLVersion(v int8) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.AddXMLVersion(v)
	})
}

// UpdateXMLVersion sets the "xml_version" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateXMLVersion() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateXMLVersion()
	})
}

// SetRssVersion sets the "rss_version" field.
func (u *FollowListsUpsertOne) SetRssVersion(v int8) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetRssVersion(v)
	})
}

// AddRssVersion adds v to the "rss_version" field.
func (u *FollowListsUpsertOne) AddRssVersion(v int8) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.AddRssVersion(v)
	})
}

// UpdateRssVersion sets the "rss_version" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateRssVersion() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateRssVersion()
	})
}

// SetURL sets the "url" field.
func (u *FollowListsUpsertOne) SetURL(v string) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateURL() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateURL()
	})
}

// SetTitle sets the "title" field.
func (u *FollowListsUpsertOne) SetTitle(v string) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateTitle() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *FollowListsUpsertOne) SetDescription(v string) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateDescription() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateDescription()
	})
}

// SetLink sets the "link" field.
func (u *FollowListsUpsertOne) SetLink(v string) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateLink() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateLink()
	})
}

// SetLinks sets the "links" field.
func (u *FollowListsUpsertOne) SetLinks(v baseFeeds.FeedLink) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetLinks(v)
	})
}

// UpdateLinks sets the "links" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateLinks() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateLinks()
	})
}

// SetItemDescription sets the "item_description" field.
func (u *FollowListsUpsertOne) SetItemDescription(v []baseFeeds.FeedItem) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetItemDescription(v)
	})
}

// UpdateItemDescription sets the "item_description" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateItemDescription() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateItemDescription()
	})
}

// SetLanguage sets the "language" field.
func (u *FollowListsUpsertOne) SetLanguage(v string) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateLanguage() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateLanguage()
	})
}

// SetDtCreated sets the "dt_created" field.
func (u *FollowListsUpsertOne) SetDtCreated(v time.Time) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetDtCreated(v)
	})
}

// UpdateDtCreated sets the "dt_created" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateDtCreated() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateDtCreated()
	})
}

// ClearDtCreated clears the value of the "dt_created" field.
func (u *FollowListsUpsertOne) ClearDtCreated() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.ClearDtCreated()
	})
}

// SetDtUpdated sets the "dt_updated" field.
func (u *FollowListsUpsertOne) SetDtUpdated(v time.Time) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetDtUpdated(v)
	})
}

// UpdateDtUpdated sets the "dt_updated" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateDtUpdated() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateDtUpdated()
	})
}

// ClearDtUpdated clears the value of the "dt_updated" field.
func (u *FollowListsUpsertOne) ClearDtUpdated() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.ClearDtUpdated()
	})
}

// SetDtLastInserted sets the "dt_last_inserted" field.
func (u *FollowListsUpsertOne) SetDtLastInserted(v time.Time) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetDtLastInserted(v)
	})
}

// UpdateDtLastInserted sets the "dt_last_inserted" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateDtLastInserted() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateDtLastInserted()
	})
}

// ClearDtLastInserted clears the value of the "dt_last_inserted" field.
func (u *FollowListsUpsertOne) ClearDtLastInserted() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.ClearDtLastInserted()
	})
}

// SetFeedCategory sets the "feed_category" field.
func (u *FollowListsUpsertOne) SetFeedCategory(v int) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetFeedCategory(v)
	})
}

// AddFeedCategory adds v to the "feed_category" field.
func (u *FollowListsUpsertOne) AddFeedCategory(v int) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.AddFeedCategory(v)
	})
}

// UpdateFeedCategory sets the "feed_category" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateFeedCategory() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateFeedCategory()
	})
}

// SetIsActive sets the "is_active" field.
func (u *FollowListsUpsertOne) SetIsActive(v bool) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateIsActive() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateIsActive()
	})
}

// SetIsFavorite sets the "is_favorite" field.
func (u *FollowListsUpsertOne) SetIsFavorite(v bool) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetIsFavorite(v)
	})
}

// UpdateIsFavorite sets the "is_favorite" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateIsFavorite() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateIsFavorite()
	})
}

// SetIsRead sets the "is_read" field.
func (u *FollowListsUpsertOne) SetIsRead(v bool) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetIsRead(v)
	})
}

// UpdateIsRead sets the "is_read" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateIsRead() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateIsRead()
	})
}

// SetIsUpdated sets the "is_updated" field.
func (u *FollowListsUpsertOne) SetIsUpdated(v bool) *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetIsUpdated(v)
	})
}

// UpdateIsUpdated sets the "is_updated" field to the value that was provided on create.
func (u *FollowListsUpsertOne) UpdateIsUpdated() *FollowListsUpsertOne {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateIsUpdated()
	})
}

// Exec executes the query.
func (u *FollowListsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FollowListsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FollowListsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FollowListsUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FollowListsUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FollowListsCreateBulk is the builder for creating many FollowLists entities in bulk.
type FollowListsCreateBulk struct {
	config
	builders []*FollowListsCreate
	conflict []sql.ConflictOption
}

// Save creates the FollowLists entities in the database.
func (flcb *FollowListsCreateBulk) Save(ctx context.Context) ([]*FollowLists, error) {
	specs := make([]*sqlgraph.CreateSpec, len(flcb.builders))
	nodes := make([]*FollowLists, len(flcb.builders))
	mutators := make([]Mutator, len(flcb.builders))
	for i := range flcb.builders {
		func(i int, root context.Context) {
			builder := flcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FollowListsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, flcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = flcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, flcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, flcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (flcb *FollowListsCreateBulk) SaveX(ctx context.Context) []*FollowLists {
	v, err := flcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (flcb *FollowListsCreateBulk) Exec(ctx context.Context) error {
	_, err := flcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (flcb *FollowListsCreateBulk) ExecX(ctx context.Context) {
	if err := flcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FollowLists.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FollowListsUpsert) {
//			SetUUID(v+v).
//		}).
//		Exec(ctx)
func (flcb *FollowListsCreateBulk) OnConflict(opts ...sql.ConflictOption) *FollowListsUpsertBulk {
	flcb.conflict = opts
	return &FollowListsUpsertBulk{
		create: flcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FollowLists.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (flcb *FollowListsCreateBulk) OnConflictColumns(columns ...string) *FollowListsUpsertBulk {
	flcb.conflict = append(flcb.conflict, sql.ConflictColumns(columns...))
	return &FollowListsUpsertBulk{
		create: flcb,
	}
}

// FollowListsUpsertBulk is the builder for "upsert"-ing
// a bulk of FollowLists nodes.
type FollowListsUpsertBulk struct {
	create *FollowListsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FollowLists.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FollowListsUpsertBulk) UpdateNewValues() *FollowListsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FollowLists.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FollowListsUpsertBulk) Ignore() *FollowListsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FollowListsUpsertBulk) DoNothing() *FollowListsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FollowListsCreateBulk.OnConflict
// documentation for more info.
func (u *FollowListsUpsertBulk) Update(set func(*FollowListsUpsert)) *FollowListsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FollowListsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUUID sets the "uuid" field.
func (u *FollowListsUpsertBulk) SetUUID(v uuid.UUID) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetUUID(v)
	})
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateUUID() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateUUID()
	})
}

// SetXMLVersion sets the "xml_version" field.
func (u *FollowListsUpsertBulk) SetXMLVersion(v int8) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetXMLVersion(v)
	})
}

// AddXMLVersion adds v to the "xml_version" field.
func (u *FollowListsUpsertBulk) AddXMLVersion(v int8) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.AddXMLVersion(v)
	})
}

// UpdateXMLVersion sets the "xml_version" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateXMLVersion() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateXMLVersion()
	})
}

// SetRssVersion sets the "rss_version" field.
func (u *FollowListsUpsertBulk) SetRssVersion(v int8) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetRssVersion(v)
	})
}

// AddRssVersion adds v to the "rss_version" field.
func (u *FollowListsUpsertBulk) AddRssVersion(v int8) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.AddRssVersion(v)
	})
}

// UpdateRssVersion sets the "rss_version" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateRssVersion() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateRssVersion()
	})
}

// SetURL sets the "url" field.
func (u *FollowListsUpsertBulk) SetURL(v string) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateURL() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateURL()
	})
}

// SetTitle sets the "title" field.
func (u *FollowListsUpsertBulk) SetTitle(v string) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateTitle() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *FollowListsUpsertBulk) SetDescription(v string) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateDescription() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateDescription()
	})
}

// SetLink sets the "link" field.
func (u *FollowListsUpsertBulk) SetLink(v string) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateLink() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateLink()
	})
}

// SetLinks sets the "links" field.
func (u *FollowListsUpsertBulk) SetLinks(v baseFeeds.FeedLink) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetLinks(v)
	})
}

// UpdateLinks sets the "links" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateLinks() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateLinks()
	})
}

// SetItemDescription sets the "item_description" field.
func (u *FollowListsUpsertBulk) SetItemDescription(v []baseFeeds.FeedItem) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetItemDescription(v)
	})
}

// UpdateItemDescription sets the "item_description" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateItemDescription() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateItemDescription()
	})
}

// SetLanguage sets the "language" field.
func (u *FollowListsUpsertBulk) SetLanguage(v string) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateLanguage() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateLanguage()
	})
}

// SetDtCreated sets the "dt_created" field.
func (u *FollowListsUpsertBulk) SetDtCreated(v time.Time) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetDtCreated(v)
	})
}

// UpdateDtCreated sets the "dt_created" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateDtCreated() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateDtCreated()
	})
}

// ClearDtCreated clears the value of the "dt_created" field.
func (u *FollowListsUpsertBulk) ClearDtCreated() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.ClearDtCreated()
	})
}

// SetDtUpdated sets the "dt_updated" field.
func (u *FollowListsUpsertBulk) SetDtUpdated(v time.Time) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetDtUpdated(v)
	})
}

// UpdateDtUpdated sets the "dt_updated" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateDtUpdated() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateDtUpdated()
	})
}

// ClearDtUpdated clears the value of the "dt_updated" field.
func (u *FollowListsUpsertBulk) ClearDtUpdated() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.ClearDtUpdated()
	})
}

// SetDtLastInserted sets the "dt_last_inserted" field.
func (u *FollowListsUpsertBulk) SetDtLastInserted(v time.Time) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetDtLastInserted(v)
	})
}

// UpdateDtLastInserted sets the "dt_last_inserted" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateDtLastInserted() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateDtLastInserted()
	})
}

// ClearDtLastInserted clears the value of the "dt_last_inserted" field.
func (u *FollowListsUpsertBulk) ClearDtLastInserted() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.ClearDtLastInserted()
	})
}

// SetFeedCategory sets the "feed_category" field.
func (u *FollowListsUpsertBulk) SetFeedCategory(v int) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetFeedCategory(v)
	})
}

// AddFeedCategory adds v to the "feed_category" field.
func (u *FollowListsUpsertBulk) AddFeedCategory(v int) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.AddFeedCategory(v)
	})
}

// UpdateFeedCategory sets the "feed_category" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateFeedCategory() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateFeedCategory()
	})
}

// SetIsActive sets the "is_active" field.
func (u *FollowListsUpsertBulk) SetIsActive(v bool) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateIsActive() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateIsActive()
	})
}

// SetIsFavorite sets the "is_favorite" field.
func (u *FollowListsUpsertBulk) SetIsFavorite(v bool) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetIsFavorite(v)
	})
}

// UpdateIsFavorite sets the "is_favorite" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateIsFavorite() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateIsFavorite()
	})
}

// SetIsRead sets the "is_read" field.
func (u *FollowListsUpsertBulk) SetIsRead(v bool) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetIsRead(v)
	})
}

// UpdateIsRead sets the "is_read" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateIsRead() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateIsRead()
	})
}

// SetIsUpdated sets the "is_updated" field.
func (u *FollowListsUpsertBulk) SetIsUpdated(v bool) *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.SetIsUpdated(v)
	})
}

// UpdateIsUpdated sets the "is_updated" field to the value that was provided on create.
func (u *FollowListsUpsertBulk) UpdateIsUpdated() *FollowListsUpsertBulk {
	return u.Update(func(s *FollowListsUpsert) {
		s.UpdateIsUpdated()
	})
}

// Exec executes the query.
func (u *FollowListsUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FollowListsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FollowListsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FollowListsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
