// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"insightstream/ent/followlist"
	"insightstream/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FollowListQuery is the builder for querying FollowList entities.
type FollowListQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	inters     []Interceptor
	predicates []predicate.FollowList
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FollowListQuery builder.
func (flq *FollowListQuery) Where(ps ...predicate.FollowList) *FollowListQuery {
	flq.predicates = append(flq.predicates, ps...)
	return flq
}

// Limit the number of records to be returned by this query.
func (flq *FollowListQuery) Limit(limit int) *FollowListQuery {
	flq.limit = &limit
	return flq
}

// Offset to start from.
func (flq *FollowListQuery) Offset(offset int) *FollowListQuery {
	flq.offset = &offset
	return flq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (flq *FollowListQuery) Unique(unique bool) *FollowListQuery {
	flq.unique = &unique
	return flq
}

// Order specifies how the records should be ordered.
func (flq *FollowListQuery) Order(o ...OrderFunc) *FollowListQuery {
	flq.order = append(flq.order, o...)
	return flq
}

// First returns the first FollowList entity from the query.
// Returns a *NotFoundError when no FollowList was found.
func (flq *FollowListQuery) First(ctx context.Context) (*FollowList, error) {
	nodes, err := flq.Limit(1).All(newQueryContext(ctx, TypeFollowList, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{followlist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (flq *FollowListQuery) FirstX(ctx context.Context) *FollowList {
	node, err := flq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FollowList ID from the query.
// Returns a *NotFoundError when no FollowList ID was found.
func (flq *FollowListQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = flq.Limit(1).IDs(newQueryContext(ctx, TypeFollowList, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{followlist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (flq *FollowListQuery) FirstIDX(ctx context.Context) int {
	id, err := flq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FollowList entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FollowList entity is found.
// Returns a *NotFoundError when no FollowList entities are found.
func (flq *FollowListQuery) Only(ctx context.Context) (*FollowList, error) {
	nodes, err := flq.Limit(2).All(newQueryContext(ctx, TypeFollowList, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{followlist.Label}
	default:
		return nil, &NotSingularError{followlist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (flq *FollowListQuery) OnlyX(ctx context.Context) *FollowList {
	node, err := flq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FollowList ID in the query.
// Returns a *NotSingularError when more than one FollowList ID is found.
// Returns a *NotFoundError when no entities are found.
func (flq *FollowListQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = flq.Limit(2).IDs(newQueryContext(ctx, TypeFollowList, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{followlist.Label}
	default:
		err = &NotSingularError{followlist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (flq *FollowListQuery) OnlyIDX(ctx context.Context) int {
	id, err := flq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FollowLists.
func (flq *FollowListQuery) All(ctx context.Context) ([]*FollowList, error) {
	ctx = newQueryContext(ctx, TypeFollowList, "All")
	if err := flq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FollowList, *FollowListQuery]()
	return withInterceptors[[]*FollowList](ctx, flq, qr, flq.inters)
}

// AllX is like All, but panics if an error occurs.
func (flq *FollowListQuery) AllX(ctx context.Context) []*FollowList {
	nodes, err := flq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FollowList IDs.
func (flq *FollowListQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = newQueryContext(ctx, TypeFollowList, "IDs")
	if err := flq.Select(followlist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (flq *FollowListQuery) IDsX(ctx context.Context) []int {
	ids, err := flq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (flq *FollowListQuery) Count(ctx context.Context) (int, error) {
	ctx = newQueryContext(ctx, TypeFollowList, "Count")
	if err := flq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, flq, querierCount[*FollowListQuery](), flq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (flq *FollowListQuery) CountX(ctx context.Context) int {
	count, err := flq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (flq *FollowListQuery) Exist(ctx context.Context) (bool, error) {
	ctx = newQueryContext(ctx, TypeFollowList, "Exist")
	switch _, err := flq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (flq *FollowListQuery) ExistX(ctx context.Context) bool {
	exist, err := flq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FollowListQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (flq *FollowListQuery) Clone() *FollowListQuery {
	if flq == nil {
		return nil
	}
	return &FollowListQuery{
		config:     flq.config,
		limit:      flq.limit,
		offset:     flq.offset,
		order:      append([]OrderFunc{}, flq.order...),
		inters:     append([]Interceptor{}, flq.inters...),
		predicates: append([]predicate.FollowList{}, flq.predicates...),
		// clone intermediate query.
		sql:    flq.sql.Clone(),
		path:   flq.path,
		unique: flq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FollowList.Query().
//		GroupBy(followlist.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (flq *FollowListQuery) GroupBy(field string, fields ...string) *FollowListGroupBy {
	flq.fields = append([]string{field}, fields...)
	grbuild := &FollowListGroupBy{build: flq}
	grbuild.flds = &flq.fields
	grbuild.label = followlist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//	}
//
//	client.FollowList.Query().
//		Select(followlist.FieldUUID).
//		Scan(ctx, &v)
func (flq *FollowListQuery) Select(fields ...string) *FollowListSelect {
	flq.fields = append(flq.fields, fields...)
	sbuild := &FollowListSelect{FollowListQuery: flq}
	sbuild.label = followlist.Label
	sbuild.flds, sbuild.scan = &flq.fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FollowListSelect configured with the given aggregations.
func (flq *FollowListQuery) Aggregate(fns ...AggregateFunc) *FollowListSelect {
	return flq.Select().Aggregate(fns...)
}

func (flq *FollowListQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range flq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, flq); err != nil {
				return err
			}
		}
	}
	for _, f := range flq.fields {
		if !followlist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if flq.path != nil {
		prev, err := flq.path(ctx)
		if err != nil {
			return err
		}
		flq.sql = prev
	}
	return nil
}

func (flq *FollowListQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FollowList, error) {
	var (
		nodes = []*FollowList{}
		_spec = flq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FollowList).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FollowList{config: flq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, flq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (flq *FollowListQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := flq.querySpec()
	_spec.Node.Columns = flq.fields
	if len(flq.fields) > 0 {
		_spec.Unique = flq.unique != nil && *flq.unique
	}
	return sqlgraph.CountNodes(ctx, flq.driver, _spec)
}

func (flq *FollowListQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   followlist.Table,
			Columns: followlist.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: followlist.FieldID,
			},
		},
		From:   flq.sql,
		Unique: true,
	}
	if unique := flq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := flq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, followlist.FieldID)
		for i := range fields {
			if fields[i] != followlist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := flq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := flq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := flq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := flq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (flq *FollowListQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(flq.driver.Dialect())
	t1 := builder.Table(followlist.Table)
	columns := flq.fields
	if len(columns) == 0 {
		columns = followlist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if flq.sql != nil {
		selector = flq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if flq.unique != nil && *flq.unique {
		selector.Distinct()
	}
	for _, p := range flq.predicates {
		p(selector)
	}
	for _, p := range flq.order {
		p(selector)
	}
	if offset := flq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := flq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FollowListGroupBy is the group-by builder for FollowList entities.
type FollowListGroupBy struct {
	selector
	build *FollowListQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (flgb *FollowListGroupBy) Aggregate(fns ...AggregateFunc) *FollowListGroupBy {
	flgb.fns = append(flgb.fns, fns...)
	return flgb
}

// Scan applies the selector query and scans the result into the given value.
func (flgb *FollowListGroupBy) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeFollowList, "GroupBy")
	if err := flgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FollowListQuery, *FollowListGroupBy](ctx, flgb.build, flgb, flgb.build.inters, v)
}

func (flgb *FollowListGroupBy) sqlScan(ctx context.Context, root *FollowListQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(flgb.fns))
	for _, fn := range flgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*flgb.flds)+len(flgb.fns))
		for _, f := range *flgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*flgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := flgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FollowListSelect is the builder for selecting fields of FollowList entities.
type FollowListSelect struct {
	*FollowListQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fls *FollowListSelect) Aggregate(fns ...AggregateFunc) *FollowListSelect {
	fls.fns = append(fls.fns, fns...)
	return fls
}

// Scan applies the selector query and scans the result into the given value.
func (fls *FollowListSelect) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeFollowList, "Select")
	if err := fls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FollowListQuery, *FollowListSelect](ctx, fls.FollowListQuery, fls, fls.inters, v)
}

func (fls *FollowListSelect) sqlScan(ctx context.Context, root *FollowListQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fls.fns))
	for _, fn := range fls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
