// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"insightstream/domain/baseFeeds"
	"insightstream/ent/followlists"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FollowListsCreate is the builder for creating a FollowLists entity.
type FollowListsCreate struct {
	config
	mutation *FollowListsMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (flc *FollowListsCreate) SetUUID(u uuid.UUID) *FollowListsCreate {
	flc.mutation.SetUUID(u)
	return flc
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableUUID(u *uuid.UUID) *FollowListsCreate {
	if u != nil {
		flc.SetUUID(*u)
	}
	return flc
}

// SetXMLVersion sets the "xml_version" field.
func (flc *FollowListsCreate) SetXMLVersion(i int8) *FollowListsCreate {
	flc.mutation.SetXMLVersion(i)
	return flc
}

// SetNillableXMLVersion sets the "xml_version" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableXMLVersion(i *int8) *FollowListsCreate {
	if i != nil {
		flc.SetXMLVersion(*i)
	}
	return flc
}

// SetRssVersion sets the "rss_version" field.
func (flc *FollowListsCreate) SetRssVersion(i int8) *FollowListsCreate {
	flc.mutation.SetRssVersion(i)
	return flc
}

// SetNillableRssVersion sets the "rss_version" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableRssVersion(i *int8) *FollowListsCreate {
	if i != nil {
		flc.SetRssVersion(*i)
	}
	return flc
}

// SetURL sets the "url" field.
func (flc *FollowListsCreate) SetURL(s string) *FollowListsCreate {
	flc.mutation.SetURL(s)
	return flc
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableURL(s *string) *FollowListsCreate {
	if s != nil {
		flc.SetURL(*s)
	}
	return flc
}

// SetTitle sets the "title" field.
func (flc *FollowListsCreate) SetTitle(s string) *FollowListsCreate {
	flc.mutation.SetTitle(s)
	return flc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableTitle(s *string) *FollowListsCreate {
	if s != nil {
		flc.SetTitle(*s)
	}
	return flc
}

// SetDescription sets the "description" field.
func (flc *FollowListsCreate) SetDescription(s string) *FollowListsCreate {
	flc.mutation.SetDescription(s)
	return flc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableDescription(s *string) *FollowListsCreate {
	if s != nil {
		flc.SetDescription(*s)
	}
	return flc
}

// SetLink sets the "link" field.
func (flc *FollowListsCreate) SetLink(s string) *FollowListsCreate {
	flc.mutation.SetLink(s)
	return flc
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableLink(s *string) *FollowListsCreate {
	if s != nil {
		flc.SetLink(*s)
	}
	return flc
}

// SetLinks sets the "links" field.
func (flc *FollowListsCreate) SetLinks(bfl baseFeeds.FeedLink) *FollowListsCreate {
	flc.mutation.SetLinks(bfl)
	return flc
}

// SetNillableLinks sets the "links" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableLinks(bfl *baseFeeds.FeedLink) *FollowListsCreate {
	if bfl != nil {
		flc.SetLinks(*bfl)
	}
	return flc
}

// SetItemDescription sets the "item_description" field.
func (flc *FollowListsCreate) SetItemDescription(bfi []baseFeeds.FeedItem) *FollowListsCreate {
	flc.mutation.SetItemDescription(bfi)
	return flc
}

// SetLanguage sets the "language" field.
func (flc *FollowListsCreate) SetLanguage(s string) *FollowListsCreate {
	flc.mutation.SetLanguage(s)
	return flc
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableLanguage(s *string) *FollowListsCreate {
	if s != nil {
		flc.SetLanguage(*s)
	}
	return flc
}

// SetDtCreated sets the "dt_created" field.
func (flc *FollowListsCreate) SetDtCreated(t time.Time) *FollowListsCreate {
	flc.mutation.SetDtCreated(t)
	return flc
}

// SetNillableDtCreated sets the "dt_created" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableDtCreated(t *time.Time) *FollowListsCreate {
	if t != nil {
		flc.SetDtCreated(*t)
	}
	return flc
}

// SetDtUpdated sets the "dt_updated" field.
func (flc *FollowListsCreate) SetDtUpdated(t time.Time) *FollowListsCreate {
	flc.mutation.SetDtUpdated(t)
	return flc
}

// SetNillableDtUpdated sets the "dt_updated" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableDtUpdated(t *time.Time) *FollowListsCreate {
	if t != nil {
		flc.SetDtUpdated(*t)
	}
	return flc
}

// SetDtLastInserted sets the "dt_last_inserted" field.
func (flc *FollowListsCreate) SetDtLastInserted(t time.Time) *FollowListsCreate {
	flc.mutation.SetDtLastInserted(t)
	return flc
}

// SetNillableDtLastInserted sets the "dt_last_inserted" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableDtLastInserted(t *time.Time) *FollowListsCreate {
	if t != nil {
		flc.SetDtLastInserted(*t)
	}
	return flc
}

// SetFeedCategory sets the "feed_category" field.
func (flc *FollowListsCreate) SetFeedCategory(i int) *FollowListsCreate {
	flc.mutation.SetFeedCategory(i)
	return flc
}

// SetNillableFeedCategory sets the "feed_category" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableFeedCategory(i *int) *FollowListsCreate {
	if i != nil {
		flc.SetFeedCategory(*i)
	}
	return flc
}

// SetIsActive sets the "is_active" field.
func (flc *FollowListsCreate) SetIsActive(b bool) *FollowListsCreate {
	flc.mutation.SetIsActive(b)
	return flc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableIsActive(b *bool) *FollowListsCreate {
	if b != nil {
		flc.SetIsActive(*b)
	}
	return flc
}

// SetIsFavorite sets the "is_favorite" field.
func (flc *FollowListsCreate) SetIsFavorite(b bool) *FollowListsCreate {
	flc.mutation.SetIsFavorite(b)
	return flc
}

// SetNillableIsFavorite sets the "is_favorite" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableIsFavorite(b *bool) *FollowListsCreate {
	if b != nil {
		flc.SetIsFavorite(*b)
	}
	return flc
}

// SetIsRead sets the "is_read" field.
func (flc *FollowListsCreate) SetIsRead(b bool) *FollowListsCreate {
	flc.mutation.SetIsRead(b)
	return flc
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableIsRead(b *bool) *FollowListsCreate {
	if b != nil {
		flc.SetIsRead(*b)
	}
	return flc
}

// SetIsUpdated sets the "is_updated" field.
func (flc *FollowListsCreate) SetIsUpdated(b bool) *FollowListsCreate {
	flc.mutation.SetIsUpdated(b)
	return flc
}

// SetNillableIsUpdated sets the "is_updated" field if the given value is not nil.
func (flc *FollowListsCreate) SetNillableIsUpdated(b *bool) *FollowListsCreate {
	if b != nil {
		flc.SetIsUpdated(*b)
	}
	return flc
}

// Mutation returns the FollowListsMutation object of the builder.
func (flc *FollowListsCreate) Mutation() *FollowListsMutation {
	return flc.mutation
}

// Save creates the FollowLists in the database.
func (flc *FollowListsCreate) Save(ctx context.Context) (*FollowLists, error) {
	flc.defaults()
	return withHooks[*FollowLists, FollowListsMutation](ctx, flc.sqlSave, flc.mutation, flc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (flc *FollowListsCreate) SaveX(ctx context.Context) *FollowLists {
	v, err := flc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (flc *FollowListsCreate) Exec(ctx context.Context) error {
	_, err := flc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (flc *FollowListsCreate) ExecX(ctx context.Context) {
	if err := flc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (flc *FollowListsCreate) defaults() {
	if _, ok := flc.mutation.UUID(); !ok {
		v := followlists.DefaultUUID()
		flc.mutation.SetUUID(v)
	}
	if _, ok := flc.mutation.XMLVersion(); !ok {
		v := followlists.DefaultXMLVersion
		flc.mutation.SetXMLVersion(v)
	}
	if _, ok := flc.mutation.RssVersion(); !ok {
		v := followlists.DefaultRssVersion
		flc.mutation.SetRssVersion(v)
	}
	if _, ok := flc.mutation.URL(); !ok {
		v := followlists.DefaultURL
		flc.mutation.SetURL(v)
	}
	if _, ok := flc.mutation.Title(); !ok {
		v := followlists.DefaultTitle
		flc.mutation.SetTitle(v)
	}
	if _, ok := flc.mutation.Description(); !ok {
		v := followlists.DefaultDescription
		flc.mutation.SetDescription(v)
	}
	if _, ok := flc.mutation.Link(); !ok {
		v := followlists.DefaultLink
		flc.mutation.SetLink(v)
	}
	if _, ok := flc.mutation.Links(); !ok {
		v := followlists.DefaultLinks
		flc.mutation.SetLinks(v)
	}
	if _, ok := flc.mutation.Language(); !ok {
		v := followlists.DefaultLanguage
		flc.mutation.SetLanguage(v)
	}
	if _, ok := flc.mutation.DtCreated(); !ok {
		v := followlists.DefaultDtCreated
		flc.mutation.SetDtCreated(v)
	}
	if _, ok := flc.mutation.DtUpdated(); !ok {
		v := followlists.DefaultDtUpdated
		flc.mutation.SetDtUpdated(v)
	}
	if _, ok := flc.mutation.DtLastInserted(); !ok {
		v := followlists.DefaultDtLastInserted
		flc.mutation.SetDtLastInserted(v)
	}
	if _, ok := flc.mutation.FeedCategory(); !ok {
		v := followlists.DefaultFeedCategory
		flc.mutation.SetFeedCategory(v)
	}
	if _, ok := flc.mutation.IsActive(); !ok {
		v := followlists.DefaultIsActive
		flc.mutation.SetIsActive(v)
	}
	if _, ok := flc.mutation.IsFavorite(); !ok {
		v := followlists.DefaultIsFavorite
		flc.mutation.SetIsFavorite(v)
	}
	if _, ok := flc.mutation.IsRead(); !ok {
		v := followlists.DefaultIsRead
		flc.mutation.SetIsRead(v)
	}
	if _, ok := flc.mutation.IsUpdated(); !ok {
		v := followlists.DefaultIsUpdated
		flc.mutation.SetIsUpdated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (flc *FollowListsCreate) check() error {
	if _, ok := flc.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "FollowLists.uuid"`)}
	}
	if _, ok := flc.mutation.XMLVersion(); !ok {
		return &ValidationError{Name: "xml_version", err: errors.New(`ent: missing required field "FollowLists.xml_version"`)}
	}
	if _, ok := flc.mutation.RssVersion(); !ok {
		return &ValidationError{Name: "rss_version", err: errors.New(`ent: missing required field "FollowLists.rss_version"`)}
	}
	if _, ok := flc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "FollowLists.url"`)}
	}
	if v, ok := flc.mutation.URL(); ok {
		if err := followlists.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "FollowLists.url": %w`, err)}
		}
	}
	if _, ok := flc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "FollowLists.title"`)}
	}
	if _, ok := flc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "FollowLists.description"`)}
	}
	if _, ok := flc.mutation.Link(); !ok {
		return &ValidationError{Name: "link", err: errors.New(`ent: missing required field "FollowLists.link"`)}
	}
	if _, ok := flc.mutation.Links(); !ok {
		return &ValidationError{Name: "links", err: errors.New(`ent: missing required field "FollowLists.links"`)}
	}
	if _, ok := flc.mutation.ItemDescription(); !ok {
		return &ValidationError{Name: "item_description", err: errors.New(`ent: missing required field "FollowLists.item_description"`)}
	}
	if _, ok := flc.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "FollowLists.language"`)}
	}
	if v, ok := flc.mutation.Language(); ok {
		if err := followlists.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "FollowLists.language": %w`, err)}
		}
	}
	if _, ok := flc.mutation.FeedCategory(); !ok {
		return &ValidationError{Name: "feed_category", err: errors.New(`ent: missing required field "FollowLists.feed_category"`)}
	}
	if _, ok := flc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "FollowLists.is_active"`)}
	}
	if _, ok := flc.mutation.IsFavorite(); !ok {
		return &ValidationError{Name: "is_favorite", err: errors.New(`ent: missing required field "FollowLists.is_favorite"`)}
	}
	if _, ok := flc.mutation.IsRead(); !ok {
		return &ValidationError{Name: "is_read", err: errors.New(`ent: missing required field "FollowLists.is_read"`)}
	}
	if _, ok := flc.mutation.IsUpdated(); !ok {
		return &ValidationError{Name: "is_updated", err: errors.New(`ent: missing required field "FollowLists.is_updated"`)}
	}
	return nil
}

func (flc *FollowListsCreate) sqlSave(ctx context.Context) (*FollowLists, error) {
	if err := flc.check(); err != nil {
		return nil, err
	}
	_node, _spec := flc.createSpec()
	if err := sqlgraph.CreateNode(ctx, flc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	flc.mutation.id = &_node.ID
	flc.mutation.done = true
	return _node, nil
}

func (flc *FollowListsCreate) createSpec() (*FollowLists, *sqlgraph.CreateSpec) {
	var (
		_node = &FollowLists{config: flc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: followlists.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: followlists.FieldID,
			},
		}
	)
	if value, ok := flc.mutation.UUID(); ok {
		_spec.SetField(followlists.FieldUUID, field.TypeUUID, value)
		_node.UUID = value
	}
	if value, ok := flc.mutation.XMLVersion(); ok {
		_spec.SetField(followlists.FieldXMLVersion, field.TypeInt8, value)
		_node.XMLVersion = value
	}
	if value, ok := flc.mutation.RssVersion(); ok {
		_spec.SetField(followlists.FieldRssVersion, field.TypeInt8, value)
		_node.RssVersion = value
	}
	if value, ok := flc.mutation.URL(); ok {
		_spec.SetField(followlists.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := flc.mutation.Title(); ok {
		_spec.SetField(followlists.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := flc.mutation.Description(); ok {
		_spec.SetField(followlists.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := flc.mutation.Link(); ok {
		_spec.SetField(followlists.FieldLink, field.TypeString, value)
		_node.Link = value
	}
	if value, ok := flc.mutation.Links(); ok {
		_spec.SetField(followlists.FieldLinks, field.TypeJSON, value)
		_node.Links = value
	}
	if value, ok := flc.mutation.ItemDescription(); ok {
		_spec.SetField(followlists.FieldItemDescription, field.TypeJSON, value)
		_node.ItemDescription = value
	}
	if value, ok := flc.mutation.Language(); ok {
		_spec.SetField(followlists.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := flc.mutation.DtCreated(); ok {
		_spec.SetField(followlists.FieldDtCreated, field.TypeTime, value)
		_node.DtCreated = value
	}
	if value, ok := flc.mutation.DtUpdated(); ok {
		_spec.SetField(followlists.FieldDtUpdated, field.TypeTime, value)
		_node.DtUpdated = value
	}
	if value, ok := flc.mutation.DtLastInserted(); ok {
		_spec.SetField(followlists.FieldDtLastInserted, field.TypeTime, value)
		_node.DtLastInserted = value
	}
	if value, ok := flc.mutation.FeedCategory(); ok {
		_spec.SetField(followlists.FieldFeedCategory, field.TypeInt, value)
		_node.FeedCategory = value
	}
	if value, ok := flc.mutation.IsActive(); ok {
		_spec.SetField(followlists.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := flc.mutation.IsFavorite(); ok {
		_spec.SetField(followlists.FieldIsFavorite, field.TypeBool, value)
		_node.IsFavorite = value
	}
	if value, ok := flc.mutation.IsRead(); ok {
		_spec.SetField(followlists.FieldIsRead, field.TypeBool, value)
		_node.IsRead = value
	}
	if value, ok := flc.mutation.IsUpdated(); ok {
		_spec.SetField(followlists.FieldIsUpdated, field.TypeBool, value)
		_node.IsUpdated = value
	}
	return _node, _spec
}

// FollowListsCreateBulk is the builder for creating many FollowLists entities in bulk.
type FollowListsCreateBulk struct {
	config
	builders []*FollowListsCreate
}

// Save creates the FollowLists entities in the database.
func (flcb *FollowListsCreateBulk) Save(ctx context.Context) ([]*FollowLists, error) {
	specs := make([]*sqlgraph.CreateSpec, len(flcb.builders))
	nodes := make([]*FollowLists, len(flcb.builders))
	mutators := make([]Mutator, len(flcb.builders))
	for i := range flcb.builders {
		func(i int, root context.Context) {
			builder := flcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FollowListsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, flcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, flcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, flcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (flcb *FollowListsCreateBulk) SaveX(ctx context.Context) []*FollowLists {
	v, err := flcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (flcb *FollowListsCreateBulk) Exec(ctx context.Context) error {
	_, err := flcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (flcb *FollowListsCreateBulk) ExecX(ctx context.Context) {
	if err := flcb.Exec(ctx); err != nil {
		panic(err)
	}
}
