// Code generated by ent, DO NOT EDIT.

package ent

import (
	"insightstream/ent/followlist"
	"insightstream/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	followlistFields := schema.FollowList{}.Fields()
	_ = followlistFields
	// followlistDescUUID is the schema descriptor for uuid field.
	followlistDescUUID := followlistFields[0].Descriptor()
	// followlist.DefaultUUID holds the default value on creation for the uuid field.
	followlist.DefaultUUID = followlistDescUUID.Default.(func() uuid.UUID)
	// followlistDescXMLVersion is the schema descriptor for xml_version field.
	followlistDescXMLVersion := followlistFields[1].Descriptor()
	// followlist.DefaultXMLVersion holds the default value on creation for the xml_version field.
	followlist.DefaultXMLVersion = followlistDescXMLVersion.Default.(int8)
	// followlistDescRssVersion is the schema descriptor for rss_version field.
	followlistDescRssVersion := followlistFields[2].Descriptor()
	// followlist.DefaultRssVersion holds the default value on creation for the rss_version field.
	followlist.DefaultRssVersion = followlistDescRssVersion.Default.(int8)
	// followlistDescDtCreated is the schema descriptor for dt_created field.
	followlistDescDtCreated := followlistFields[10].Descriptor()
	// followlist.DefaultDtCreated holds the default value on creation for the dt_created field.
	followlist.DefaultDtCreated = followlistDescDtCreated.Default.(time.Time)
	// followlistDescDtUpdated is the schema descriptor for dt_updated field.
	followlistDescDtUpdated := followlistFields[11].Descriptor()
	// followlist.DefaultDtUpdated holds the default value on creation for the dt_updated field.
	followlist.DefaultDtUpdated = followlistDescDtUpdated.Default.(time.Time)
	// followlistDescFeedCategory is the schema descriptor for feed_category field.
	followlistDescFeedCategory := followlistFields[12].Descriptor()
	// followlist.DefaultFeedCategory holds the default value on creation for the feed_category field.
	followlist.DefaultFeedCategory = followlistDescFeedCategory.Default.(int)
	// followlistDescIsActive is the schema descriptor for is_active field.
	followlistDescIsActive := followlistFields[13].Descriptor()
	// followlist.DefaultIsActive holds the default value on creation for the is_active field.
	followlist.DefaultIsActive = followlistDescIsActive.Default.(bool)
	// followlistDescIsFavorite is the schema descriptor for is_favorite field.
	followlistDescIsFavorite := followlistFields[14].Descriptor()
	// followlist.DefaultIsFavorite holds the default value on creation for the is_favorite field.
	followlist.DefaultIsFavorite = followlistDescIsFavorite.Default.(bool)
	// followlistDescIsRead is the schema descriptor for is_read field.
	followlistDescIsRead := followlistFields[15].Descriptor()
	// followlist.DefaultIsRead holds the default value on creation for the is_read field.
	followlist.DefaultIsRead = followlistDescIsRead.Default.(bool)
	// followlistDescIsUpdated is the schema descriptor for is_updated field.
	followlistDescIsUpdated := followlistFields[16].Descriptor()
	// followlist.DefaultIsUpdated holds the default value on creation for the is_updated field.
	followlist.DefaultIsUpdated = followlistDescIsUpdated.Default.(bool)
}
