// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CooccurrenceNetworkPoolsColumns holds the columns for the "cooccurrence_network_pools" table.
	CooccurrenceNetworkPoolsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "site_url", Type: field.TypeString, Unique: true},
		{Name: "titles", Type: field.TypeJSON},
		{Name: "descriptions", Type: field.TypeJSON},
	}
	// CooccurrenceNetworkPoolsTable holds the schema information for the "cooccurrence_network_pools" table.
	CooccurrenceNetworkPoolsTable = &schema.Table{
		Name:       "cooccurrence_network_pools",
		Columns:    CooccurrenceNetworkPoolsColumns,
		PrimaryKey: []*schema.Column{CooccurrenceNetworkPoolsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "cooccurrencenetworkpool_id",
				Unique:  true,
				Columns: []*schema.Column{CooccurrenceNetworkPoolsColumns[0]},
			},
			{
				Name:    "cooccurrencenetworkpool_id_site_url",
				Unique:  true,
				Columns: []*schema.Column{CooccurrenceNetworkPoolsColumns[0], CooccurrenceNetworkPoolsColumns[1]},
			},
		},
	}
	// FeedsColumns holds the columns for the "feeds" table.
	FeedsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "site_url", Type: field.TypeString, Default: ""},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "feed_url", Type: field.TypeString, Default: ""},
		{Name: "language", Type: field.TypeString, Default: ""},
		{Name: "dt_created", Type: field.TypeTime},
		{Name: "dt_updated", Type: field.TypeTime},
		{Name: "favorites", Type: field.TypeInt64, Default: 0},
	}
	// FeedsTable holds the schema information for the "feeds" table.
	FeedsTable = &schema.Table{
		Name:       "feeds",
		Columns:    FeedsColumns,
		PrimaryKey: []*schema.Column{FeedsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "feeds_id",
				Unique:  true,
				Columns: []*schema.Column{FeedsColumns[0]},
			},
			{
				Name:    "feeds_site_url_feed_url",
				Unique:  true,
				Columns: []*schema.Column{FeedsColumns[1], FeedsColumns[4]},
			},
			{
				Name:    "feeds_id_feed_url",
				Unique:  true,
				Columns: []*schema.Column{FeedsColumns[0], FeedsColumns[4]},
			},
			{
				Name:    "feeds_id_dt_updated",
				Unique:  true,
				Columns: []*schema.Column{FeedsColumns[0], FeedsColumns[7]},
			},
		},
	}
	// FollowListsColumns holds the columns for the "follow_lists" table.
	FollowListsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeUUID},
		{Name: "xml_version", Type: field.TypeInt8, Default: 1},
		{Name: "rss_version", Type: field.TypeInt8, Default: 2},
		{Name: "url", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "link", Type: field.TypeString},
		{Name: "links", Type: field.TypeJSON},
		{Name: "item_description", Type: field.TypeJSON},
		{Name: "language", Type: field.TypeString},
		{Name: "dt_created", Type: field.TypeTime},
		{Name: "dt_updated", Type: field.TypeTime},
		{Name: "dt_last_inserted", Type: field.TypeTime},
		{Name: "feed_category", Type: field.TypeInt, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_favorite", Type: field.TypeBool, Default: false},
		{Name: "is_read", Type: field.TypeBool, Default: false},
		{Name: "is_updated", Type: field.TypeBool, Default: false},
	}
	// FollowListsTable holds the schema information for the "follow_lists" table.
	FollowListsTable = &schema.Table{
		Name:       "follow_lists",
		Columns:    FollowListsColumns,
		PrimaryKey: []*schema.Column{FollowListsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "followlist_uuid",
				Unique:  true,
				Columns: []*schema.Column{FollowListsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "username", Type: field.TypeString},
		{Name: "hashed_password", Type: field.TypeBytes},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "users_id",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[0]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CooccurrenceNetworkPoolsTable,
		FeedsTable,
		FollowListsTable,
		UsersTable,
	}
)

func init() {
}
